# -*- coding: utf-8 -*-
"""Auto_ST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xaakFUOxD_M4xUGfmEHuojVPpae1-oOo
"""

import pywt
import matplotlib.pyplot as plt
import numpy as np
import pywt.data
import cv2
from PIL import Image
import os
from google.colab.patches import cv2_imshow

def sw(img_path,wavelet='haar',level=1):


  img1=Image.open(img_path[0]).convert('RGB')
  img2=Image.open(img_path[1]).convert('RGB')
  x=np.array(img1)
  y=np.array(img2)
  img_1= cv2.cvtColor(x, cv2.COLOR_RGB2BGR)
  img_2= cv2.cvtColor(y, cv2.COLOR_RGB2BGR)

  img_2 = cv2.resize(y, (img_1.shape[0],img_1.shape[1]))

  Red_Input_Image1=img_1[:,:,0]

  Green_Input_Image1=img_1[:,:,1]

  Blue_Input_Image1=img_1[:,:,2]

  LAr1,LDr1=pywt.swt2(Red_Input_Image1,wavelet=wavelet,level=level,norm=True)[0]
  LAg1,LDg1=pywt.swt2(Green_Input_Image1,wavelet=wavelet,level=level,norm=True)[0]
  LAb1,LDb1=pywt.swt2(Blue_Input_Image1,wavelet=wavelet,level=level,norm=True)[0]

  Red_Input_Image2=img_2[:,:,0]

  Green_Input_Image2=img_2[:,:,1]

  Blue_Input_Image2=img_2[:,:,2]

  LAr2,LDr2=pywt.swt2(Red_Input_Image2,wavelet=wavelet,level=level,norm=True)[0]
  LAg2,LDg2=pywt.swt2(Green_Input_Image2,wavelet=wavelet,level=level,norm=True)[0]
  LAb2,LDb2=pywt.swt2(Blue_Input_Image2,wavelet=wavelet,level=level,norm=True)[0]

  LAr=np.add(LAr1,LAr2)
  LAg=np.add(LAg1,LAg2)
  LAb=np.add(LAb1,LAb2)


  LDr=np.add(LDr1,LDr2)/2
  LDg=np.add(LDg1,LDg2)/2
  LDb=np.add(LDb1,LDb2)/2


  R=pywt.iswt2((LAr,LDr),wavelet=wavelet)
  G=pywt.iswt2((LAg,LDg),wavelet=wavelet)
  B=pywt.iswt2((LAb,LDb),wavelet=wavelet)

  imgx= np.zeros([R.shape[0], R.shape[1], 3], dtype=np.uint8)
  imgx[:,:,0]=R
  imgx[:,:,1]=G
  imgx[:,:,2]=B
  return imgx




#im=sw(img_path)
#cv2_imshow(im)



l=os.listdir('/content/drive/My Drive/Dataset/Original')
l.sort()

l[:5]

for i in range(0,len(l),2):

  path1='/content/drive/My Drive/Dataset/Original/'+l[i]
  path2='/content/drive/My Drive/Dataset/Original/'+l[i+1]

  img_path=[]
  img_path.append(path1)
  img_path.append(path2)
  im=sw(img_path)

  #if i %  == 0:
  #cv2_imshow(im)
  #print(l[i])
  #print(l[i+1])
  
  cv2.imwrite('/content/drive/My Drive/Output ST/'+l[i][0:l[i].index('.')]+'.jpeg',im)

l[0][0:l[0].index('.')]

